import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/libs/utils';
import localFont from 'next/font/local';
import { ThemeProvider } from '@/providers/theme-provider';
import { Jersey_15 } from 'next/font/google';

const mainFont = localFont({
  src: '../fonts/IRANSansXV.woff2',
  variable: '--font-iransansxv',
  display: 'block',
});

const jersey = Jersey_15({
  weight: '400',
  subsets: ['latin'],
  display: 'block',
  variable: '--font-jersey',
});

export const metadata: Metadata = {
  title: 'Movie App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir='rtl' lang='fa-Ir'>
      <body
        className={cn(
          'dark:bg-darkest font-sansX',
          mainFont.variable,
          jersey.variable,
        )}
      >
        <ThemeProvider attribute='class' disableTransitionOnChange enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
