import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/libs/utils';
import localFont from 'next/font/local';
import Navbar from '@/components/navbar/navbar';

const mainFont = localFont({
  src: '../fonts/IRANSansXV.woff2',
  variable: '--font-iransansxv',
  display: 'block',
});

export const metadata: Metadata = {
  title: 'Movie App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir='rtl' lang='fa-Ir'>
      <body className={cn('font-sansX', mainFont.variable)}>{children}</body>
    </html>
  );
}
